[tool.poetry]
name = "desktop"
version = "0.1.0"
description = ""
authors = ["KorenbAS78 <KorenbAS78@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
